spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
    password: redispwd
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1ms
    timeout: 1000ms

#mybatis:
#  #配置mapper文件所在地，在 resources 目录下的mapper目录的*xml文件
#  mapper-locations: classpath:mybatis/*.xml

info:
    app:
      version: 0.0.1
      name: reidsapp-Dev

