spring:
  profiles:
    active: dev
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      url: jdbc:mysql://172.16.63.190:3306/corp_default?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: rylai
      password: rylai
mybatis:
  #配置mapper文件所在地，在 resources 目录下的mapper目录的*xml文件
  mapper-locations: classpath:mybatis/*.xml

info:
    app:
      version: 0.0.1
      name: assetsapp-Dev

