spring:
  profiles:
    active: prod

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/corp0001?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
  #配置mapper文件所在地，在 resources 目录下的mapper目录的*xml文件
  mapper-locations: classpath:mybatis/*.xml

info:
    app:
      version: 0.0.1
      name: inventory-server-prod
